### ISSUE TITLE
Story 5 - Monthly View GUI

### ISSUE THREAD

**Issue by Necro991** [Necro991/CSC4350-Calendar#7]

**Comment by NadiyaNoor** [comment]
![monthly gui](https://user-images.githubusercontent.com/32606236/45840249-681b8700-bce4-11e8-8104-ca6d84a44c2d.jpg)

**Comment by NadiyaNoor** [comment]
![Image (8).jpg](https://images.zenhubusercontent.com/5b92fe5f6eb3db57432749ec/82b229b6-92f7-482f-bc73-677b02c187ca)


Updated Monthly View
